### ISSUE TITLE
Migrate to .NET Standard

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.Markdownlint#6]
Addin should support .NET Core and Cake CoreCLR runner

Stuff which needs to be done:
* Remove dependency to `Newtonsoft.Json` as Costura.Fody is not compatible with .NET Core 
* Convert solution to Visual Studio 2017
* Add .NET Standard 2.0 target
* Use Visual Studio 2017 AppVeyor image

For an example see https://github.com/cake-contrib/Cake.Issues/pull/6

**Comment by t-johnson** [comment]
I can take this on.  are you aiming to target .net standard 1.6 or 2.0 ?

**Comment by pascalberger** [comment]
@t-johnson Thanks, this would be great.

Same instructions as for https://github.com/cake-contrib/Cake.Issues/issues/4#issuecomment-336357489. But additionally Costura.Fody won't work with .NET Core, so we need to find another solution how to embed referenced assemblies which works with .NET Core.
